stages:
#- name: Build
#  steps:
#  - runScriptConfig:
#      image: nginx:stable
#      shellScript: |-
#        ls
#        cp index.html /usr/share/nginx/html/index.html
#        sleep 5s
#        curl localhost:80 || exit 1
- name: Build and Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: gcr.io/devops-sandbox-20200519/nikhilpn-reg/demo/nginx:${CICD_GIT_TAG}
      pushRemote: true
      registry: gcr.io

- name: Deploy
  steps:
  - applyYamlConfig:
      path: deploy/nginx-prod.yaml
