stages:
- name: Build and Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: gcr.io/devops-sandbox-20200519/nikhilpn-reg/demo/nginx:${CICD_GIT_TAG}
      pushRemote: true
      registry: gcr.io
    when:
      event:
        include:
        - tag
- name: Deploy
  steps:
  - applyYamlConfig:
      path: deploy/nginx-prod.yaml
    when:
      event:
        include:
        - tag
- name: PublishCatlog
  steps:
  - publishCatalogConfig:
      path: deploy
      catalogTemplate: nginx-web
      version: latest
      gitUrl: git@github.com:nikhil-cldcvr/spinnkaer-canarry-web-app.git
      gitBranch: rancher
      gitAuthor: nikhil
      gitEmail: nikhil.pandit@cldcvr.com
    envFrom:
    - sourceName: git-key
      sourceKey: DEPLOY_KEY
      targetKey: DEPLOY_KEY
    when:
      event:
        include:
        - tag
