apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-server-canary
  namespace: spinnaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web-server
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
      labels:
        app: simple-web-server
        release: simple-web-server-canary
    spec:
      containers:
        - env:
            - name: Release
              value: Canary
          image: 'densikatshine/simple-web-server:${trigger[''tag'']}'
          name: simple-web-server
          ports:
            - containerPort: 8080

