apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: eks-app
  name: simple-web-server
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-web-server
  type: LoadBalancer
status:
  loadBalancer: {}
