apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-server
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: simple-web-server
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
      labels:
        app: simple-web-server
    spec:
      containers:
        - env:
            - name: Release
              value: Production
          image: gcr.io/devops-sandbox-20200519/nikhilpn-reg/sinnaker/simple-wepapp:latest
          name: simple-web-server
          ports:
            - containerPort: 8080
