apiVersion: v1
kind: Service
metadata:
  name: simple-web-server
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: simple-web-server
  type: LoadBalancer
